/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#0052dd',
        'surface-container-high': '#e8e8e8',
        'tertiary-fixed': '#ffdbd0',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fff1ed',
        'primary': '#004ccd',
        'on-primary': '#ffffff',
        'surface': '#f9f9f9',
        'on-secondary': '#ffffff',
        'secondary-container': '#a4ecec',
        'inverse-surface': '#2f3131',
        'on-secondary-fixed': '#002020',
        'surface-container': '#eeeeee',
        'surface-bright': '#f9f9f9',
        'on-surface': '#1a1c1c',
        'on-secondary-container': '#1f6d6d',
        'on-primary-fixed': '#00174c',
        'outline-variant': '#c3c6d8',
        'on-surface-variant': '#424656',
        'surface-container-low': '#f3f3f3',
        'on-secondary-fixed-variant': '#004f4f',
        'on-primary-fixed-variant': '#003da9',
        'surface-dim': '#dadada',
        'primary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#8bd3d2',
        'on-background': '#1a1c1c',
        'tertiary-container': '#c84000',
        'on-error': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#ffb59d',
        'background': '#f9f9f9',
        'inverse-primary': '#b4c5ff',
        'on-primary-container': '#f3f3ff',
        'primary-container': '#0f62fe',
        'surface-variant': '#e2e2e2',
        'secondary-fixed': '#a7efee',
        'on-error-container': '#93000a',
        'secondary': '#196969',
        'surface-container-highest': '#e2e2e2',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b4c5ff',
        'tertiary': '#9e3100',
        'on-tertiary-fixed-variant': '#832700',
        'surface-container-lowest': '#ffffff',
        'outline': '#737687',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        xl: '32px',
        'margin-mobile': '16px',
        '2xl': '48px',
        gutter: '24px',
        'container-max': '1440px',
        sm: '8px',
        '3xl': '64px',
        md: '16px',
        base: '4px',
        lg: '24px',
      },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans'],
        'display-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-sm': ['Inter'],
        'label-sm': ['Inter'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'code': ['Courier Prime'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'code': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
