before:
  hooks:
    - go mod tidy
builds:
  - id: dns-server
    binary: dns-server
    main: ./backend/cmd/dns-server
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-snapshot'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
