services:
  dns-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: production
    image: dns-server:latest
    container_name: dns-server
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - dns-data:/app/data
    command: ["./dns-server", "--dns-addr", "192.168.0.111"]

volumes:
  dns-data:
